include(cmake/CPM.cmake)

function(add_external_dependencies)

CPMAddPackage(
  NAME curl
  GITHUB_REPOSITORY curl/curl
  GIT_TAG curl-8_2_1
  OPTIONS 
  "CURL_ENABLE_SSL OFF" "HTTP_ONLY ON" "BUILD_CURL_EXE OFF" "BUILD_SHARED_LIBS OFF"  
  "CURL_BROTLI OFF" "USE_LIBIDN2 OFF" "CURL_USE_LIBSSH2 OFF" "CURL_USE_LIBSSH OFF"
  "CMAKE_POSITION_INDEPENDENT_CODE ON"
  "USE_ZLIB OFF" "CURL_DISABLE_CRYPTO_AUTH ON" "USE_LIBSSH2 OFF" "USE_LIBSSH OFF"
)

endfunction()